# Generated by Django 3.0.5 on 2020-04-28 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CASE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('maker', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=10)),
                ('board', models.CharField(max_length=10)),
                ('price', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('maker', models.CharField(max_length=10)),
                ('gen', models.CharField(max_length=20)),
                ('socket', models.CharField(max_length=20)),
                ('core', models.IntegerField(max_length=3)),
                ('thread', models.IntegerField(max_length=3)),
                ('clock', models.IntegerField(max_length=4)),
                ('price', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HDD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('maker', models.CharField(max_length=20)),
                ('capacity', models.IntegerField(max_length=2)),
                ('rotspeed', models.IntegerField(max_length=5)),
                ('price', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('maker', models.CharField(max_length=10)),
                ('chipset', models.CharField(max_length=20)),
                ('socket', models.CharField(max_length=20)),
                ('form', models.CharField(max_length=10)),
                ('price', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('maker', models.CharField(max_length=20)),
                ('capacity', models.IntegerField(max_length=4)),
                ('cert', models.CharField(max_length=10)),
                ('price', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('maker', models.CharField(max_length=20)),
                ('gen', models.CharField(max_length=10)),
                ('capacity', models.IntegerField(max_length=3)),
                ('clock', models.IntegerField(max_length=5)),
                ('price', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SSD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('maker', models.CharField(max_length=20)),
                ('nvme', models.BooleanField()),
                ('capacity', models.IntegerField(max_length=4)),
                ('memtype', models.CharField(max_length=10)),
                ('price', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VGA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('maker', models.CharField(max_length=20)),
                ('chipmaker', models.CharField(max_length=10)),
                ('chipset', models.CharField(max_length=20)),
                ('memcap', models.IntegerField(max_length=3)),
                ('length', models.IntegerField(max_length=3)),
                ('price', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tot_price', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quote_maker.CASE')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quote_maker.CPU')),
                ('hdd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quote_maker.HDD')),
                ('mb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quote_maker.MB')),
                ('psu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quote_maker.PSU')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quote_maker.RAM')),
                ('ssd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quote_maker.SSD')),
                ('vga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quote_maker.VGA')),
            ],
        ),
    ]
