# Generated by Django 3.0.5 on 2020-04-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_maker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='clock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='core',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='thread',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='rotspeed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mb',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='psu',
            name='capacity',
            field=models.IntegerField(verbose_name=4),
        ),
        migrations.AlterField(
            model_name='psu',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ram',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ram',
            name='clock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ram',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vga',
            name='length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vga',
            name='memcap',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vga',
            name='price',
            field=models.IntegerField(),
        ),
    ]
