# Generated by Django 3.0.5 on 2020-05-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_maker', '0002_auto_20200429_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('usage', models.CharField(max_length=20)),
            ],
        ),
    ]
